//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPos.Kasa.SyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncService.ISyncService")]
    public interface ISyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/Hello", ReplyAction="http://tempuri.org/ISyncService/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/JediniceMere", ReplyAction="http://tempuri.org/ISyncService/JediniceMereResponse")]
        System.Collections.Generic.List<AbcPos.Core.Models.JedinicaMere> JediniceMere();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/Pdv", ReplyAction="http://tempuri.org/ISyncService/PdvResponse")]
        System.Collections.Generic.List<AbcPos.Core.Models.Pdv> Pdv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/VratiArtikle", ReplyAction="http://tempuri.org/ISyncService/VratiArtikleResponse")]
        System.Collections.Generic.List<AbcPos.Core.Models.Artikal> VratiArtikle(string idRadnje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/VratiRadnju", ReplyAction="http://tempuri.org/ISyncService/VratiRadnjuResponse")]
        AbcPos.Core.Models.Radnja VratiRadnju(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/VratiZalihe", ReplyAction="http://tempuri.org/ISyncService/VratiZaliheResponse")]
        System.Collections.Generic.List<AbcPos.Core.Models.Zaliha> VratiZalihe(string idRadnje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/VratiRacune", ReplyAction="http://tempuri.org/ISyncService/VratiRacuneResponse")]
        System.Collections.Generic.List<AbcPos.Core.Models.Racun> VratiRacune(string idRadnje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SinhronizujRacune", ReplyAction="http://tempuri.org/ISyncService/SinhronizujRacuneResponse")]
        void SinhronizujRacune(System.Collections.Generic.List<AbcPos.Core.Models.Racun> racuni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SacuvajRacun", ReplyAction="http://tempuri.org/ISyncService/SacuvajRacunResponse")]
        void SacuvajRacun(AbcPos.Core.Models.Racun racun);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncServiceChannel : AbcPos.Kasa.SyncService.ISyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncServiceClient : System.ServiceModel.ClientBase<AbcPos.Kasa.SyncService.ISyncService>, AbcPos.Kasa.SyncService.ISyncService {
        
        public SyncServiceClient() {
        }
        
        public SyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public System.Collections.Generic.List<AbcPos.Core.Models.JedinicaMere> JediniceMere() {
            return base.Channel.JediniceMere();
        }
        
        public System.Collections.Generic.List<AbcPos.Core.Models.Pdv> Pdv() {
            return base.Channel.Pdv();
        }
        
        public System.Collections.Generic.List<AbcPos.Core.Models.Artikal> VratiArtikle(string idRadnje) {
            return base.Channel.VratiArtikle(idRadnje);
        }
        
        public AbcPos.Core.Models.Radnja VratiRadnju(string id) {
            return base.Channel.VratiRadnju(id);
        }
        
        public System.Collections.Generic.List<AbcPos.Core.Models.Zaliha> VratiZalihe(string idRadnje) {
            return base.Channel.VratiZalihe(idRadnje);
        }
        
        public System.Collections.Generic.List<AbcPos.Core.Models.Racun> VratiRacune(string idRadnje) {
            return base.Channel.VratiRacune(idRadnje);
        }
        
        public void SinhronizujRacune(System.Collections.Generic.List<AbcPos.Core.Models.Racun> racuni) {
            base.Channel.SinhronizujRacune(racuni);
        }
        
        public void SacuvajRacun(AbcPos.Core.Models.Racun racun) {
            base.Channel.SacuvajRacun(racun);
        }
    }
}
