//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPos.BackOffice.Win.Services.BackendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artikal", Namespace="http://schemas.datacontract.org/2004/07/AbcPos.Web.Models")]
    [System.SerializableAttribute()]
    public partial class Artikal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JedinicaMereIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OznakaJediniceMereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PdvIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdvStopaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barkod {
            get {
                return this.BarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodField, value) != true)) {
                    this.BarkodField = value;
                    this.RaisePropertyChanged("Barkod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JedinicaMereID {
            get {
                return this.JedinicaMereIDField;
            }
            set {
                if ((this.JedinicaMereIDField.Equals(value) != true)) {
                    this.JedinicaMereIDField = value;
                    this.RaisePropertyChanged("JedinicaMereID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OznakaJediniceMere {
            get {
                return this.OznakaJediniceMereField;
            }
            set {
                if ((object.ReferenceEquals(this.OznakaJediniceMereField, value) != true)) {
                    this.OznakaJediniceMereField = value;
                    this.RaisePropertyChanged("OznakaJediniceMere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PdvID {
            get {
                return this.PdvIDField;
            }
            set {
                if ((this.PdvIDField.Equals(value) != true)) {
                    this.PdvIDField = value;
                    this.RaisePropertyChanged("PdvID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdvStopa {
            get {
                return this.PdvStopaField;
            }
            set {
                if ((object.ReferenceEquals(this.PdvStopaField, value) != true)) {
                    this.PdvStopaField = value;
                    this.RaisePropertyChanged("PdvStopa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifra {
            get {
                return this.SifraField;
            }
            set {
                if ((object.ReferenceEquals(this.SifraField, value) != true)) {
                    this.SifraField = value;
                    this.RaisePropertyChanged("Sifra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValue", Namespace="http://schemas.datacontract.org/2004/07/AbcPos.Web.Models")]
    [System.SerializableAttribute()]
    public partial class KeyValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.BackendService.BackendService")]
    public interface BackendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackendService/VratiArtikle", ReplyAction="http://tempuri.org/BackendService/VratiArtikleResponse")]
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> VratiArtikle();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BackendService/VratiArtikle", ReplyAction="http://tempuri.org/BackendService/VratiArtikleResponse")]
        System.IAsyncResult BeginVratiArtikle(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> EndVratiArtikle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackendService/VratiJediniceMera", ReplyAction="http://tempuri.org/BackendService/VratiJediniceMeraResponse")]
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> VratiJediniceMera();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BackendService/VratiJediniceMera", ReplyAction="http://tempuri.org/BackendService/VratiJediniceMeraResponse")]
        System.IAsyncResult BeginVratiJediniceMera(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> EndVratiJediniceMera(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackendService/VratiPdv", ReplyAction="http://tempuri.org/BackendService/VratiPdvResponse")]
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> VratiPdv();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BackendService/VratiPdv", ReplyAction="http://tempuri.org/BackendService/VratiPdvResponse")]
        System.IAsyncResult BeginVratiPdv(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> EndVratiPdv(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackendService/SacuvajArtikal", ReplyAction="http://tempuri.org/BackendService/SacuvajArtikalResponse")]
        int SacuvajArtikal(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BackendService/SacuvajArtikal", ReplyAction="http://tempuri.org/BackendService/SacuvajArtikalResponse")]
        System.IAsyncResult BeginSacuvajArtikal(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal, System.AsyncCallback callback, object asyncState);
        
        int EndSacuvajArtikal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackendService/Ping", ReplyAction="http://tempuri.org/BackendService/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BackendService/Ping", ReplyAction="http://tempuri.org/BackendService/PingResponse")]
        System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState);
        
        void EndPing(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BackendServiceChannel : AbcPos.BackOffice.Win.Services.BackendService.BackendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VratiArtikleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VratiArtikleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VratiJediniceMeraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VratiJediniceMeraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VratiPdvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VratiPdvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SacuvajArtikalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SacuvajArtikalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackendServiceClient : System.ServiceModel.ClientBase<AbcPos.BackOffice.Win.Services.BackendService.BackendService>, AbcPos.BackOffice.Win.Services.BackendService.BackendService {
        
        private BeginOperationDelegate onBeginVratiArtikleDelegate;
        
        private EndOperationDelegate onEndVratiArtikleDelegate;
        
        private System.Threading.SendOrPostCallback onVratiArtikleCompletedDelegate;
        
        private BeginOperationDelegate onBeginVratiJediniceMeraDelegate;
        
        private EndOperationDelegate onEndVratiJediniceMeraDelegate;
        
        private System.Threading.SendOrPostCallback onVratiJediniceMeraCompletedDelegate;
        
        private BeginOperationDelegate onBeginVratiPdvDelegate;
        
        private EndOperationDelegate onEndVratiPdvDelegate;
        
        private System.Threading.SendOrPostCallback onVratiPdvCompletedDelegate;
        
        private BeginOperationDelegate onBeginSacuvajArtikalDelegate;
        
        private EndOperationDelegate onEndSacuvajArtikalDelegate;
        
        private System.Threading.SendOrPostCallback onSacuvajArtikalCompletedDelegate;
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        public BackendServiceClient() {
        }
        
        public BackendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<VratiArtikleCompletedEventArgs> VratiArtikleCompleted;
        
        public event System.EventHandler<VratiJediniceMeraCompletedEventArgs> VratiJediniceMeraCompleted;
        
        public event System.EventHandler<VratiPdvCompletedEventArgs> VratiPdvCompleted;
        
        public event System.EventHandler<SacuvajArtikalCompletedEventArgs> SacuvajArtikalCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PingCompleted;
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> VratiArtikle() {
            return base.Channel.VratiArtikle();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVratiArtikle(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVratiArtikle(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> EndVratiArtikle(System.IAsyncResult result) {
            return base.Channel.EndVratiArtikle(result);
        }
        
        private System.IAsyncResult OnBeginVratiArtikle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginVratiArtikle(callback, asyncState);
        }
        
        private object[] OnEndVratiArtikle(System.IAsyncResult result) {
            System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.Artikal> retVal = this.EndVratiArtikle(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVratiArtikleCompleted(object state) {
            if ((this.VratiArtikleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VratiArtikleCompleted(this, new VratiArtikleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VratiArtikleAsync() {
            this.VratiArtikleAsync(null);
        }
        
        public void VratiArtikleAsync(object userState) {
            if ((this.onBeginVratiArtikleDelegate == null)) {
                this.onBeginVratiArtikleDelegate = new BeginOperationDelegate(this.OnBeginVratiArtikle);
            }
            if ((this.onEndVratiArtikleDelegate == null)) {
                this.onEndVratiArtikleDelegate = new EndOperationDelegate(this.OnEndVratiArtikle);
            }
            if ((this.onVratiArtikleCompletedDelegate == null)) {
                this.onVratiArtikleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVratiArtikleCompleted);
            }
            base.InvokeAsync(this.onBeginVratiArtikleDelegate, null, this.onEndVratiArtikleDelegate, this.onVratiArtikleCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> VratiJediniceMera() {
            return base.Channel.VratiJediniceMera();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVratiJediniceMera(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVratiJediniceMera(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> EndVratiJediniceMera(System.IAsyncResult result) {
            return base.Channel.EndVratiJediniceMera(result);
        }
        
        private System.IAsyncResult OnBeginVratiJediniceMera(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginVratiJediniceMera(callback, asyncState);
        }
        
        private object[] OnEndVratiJediniceMera(System.IAsyncResult result) {
            System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> retVal = this.EndVratiJediniceMera(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVratiJediniceMeraCompleted(object state) {
            if ((this.VratiJediniceMeraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VratiJediniceMeraCompleted(this, new VratiJediniceMeraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VratiJediniceMeraAsync() {
            this.VratiJediniceMeraAsync(null);
        }
        
        public void VratiJediniceMeraAsync(object userState) {
            if ((this.onBeginVratiJediniceMeraDelegate == null)) {
                this.onBeginVratiJediniceMeraDelegate = new BeginOperationDelegate(this.OnBeginVratiJediniceMera);
            }
            if ((this.onEndVratiJediniceMeraDelegate == null)) {
                this.onEndVratiJediniceMeraDelegate = new EndOperationDelegate(this.OnEndVratiJediniceMera);
            }
            if ((this.onVratiJediniceMeraCompletedDelegate == null)) {
                this.onVratiJediniceMeraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVratiJediniceMeraCompleted);
            }
            base.InvokeAsync(this.onBeginVratiJediniceMeraDelegate, null, this.onEndVratiJediniceMeraDelegate, this.onVratiJediniceMeraCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> VratiPdv() {
            return base.Channel.VratiPdv();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVratiPdv(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVratiPdv(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> EndVratiPdv(System.IAsyncResult result) {
            return base.Channel.EndVratiPdv(result);
        }
        
        private System.IAsyncResult OnBeginVratiPdv(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginVratiPdv(callback, asyncState);
        }
        
        private object[] OnEndVratiPdv(System.IAsyncResult result) {
            System.Collections.Generic.List<AbcPos.BackOffice.Win.Services.BackendService.KeyValue> retVal = this.EndVratiPdv(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVratiPdvCompleted(object state) {
            if ((this.VratiPdvCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VratiPdvCompleted(this, new VratiPdvCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VratiPdvAsync() {
            this.VratiPdvAsync(null);
        }
        
        public void VratiPdvAsync(object userState) {
            if ((this.onBeginVratiPdvDelegate == null)) {
                this.onBeginVratiPdvDelegate = new BeginOperationDelegate(this.OnBeginVratiPdv);
            }
            if ((this.onEndVratiPdvDelegate == null)) {
                this.onEndVratiPdvDelegate = new EndOperationDelegate(this.OnEndVratiPdv);
            }
            if ((this.onVratiPdvCompletedDelegate == null)) {
                this.onVratiPdvCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVratiPdvCompleted);
            }
            base.InvokeAsync(this.onBeginVratiPdvDelegate, null, this.onEndVratiPdvDelegate, this.onVratiPdvCompletedDelegate, userState);
        }
        
        public int SacuvajArtikal(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal) {
            return base.Channel.SacuvajArtikal(artikal);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSacuvajArtikal(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSacuvajArtikal(artikal, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSacuvajArtikal(System.IAsyncResult result) {
            return base.Channel.EndSacuvajArtikal(result);
        }
        
        private System.IAsyncResult OnBeginSacuvajArtikal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal = ((AbcPos.BackOffice.Win.Services.BackendService.Artikal)(inValues[0]));
            return this.BeginSacuvajArtikal(artikal, callback, asyncState);
        }
        
        private object[] OnEndSacuvajArtikal(System.IAsyncResult result) {
            int retVal = this.EndSacuvajArtikal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSacuvajArtikalCompleted(object state) {
            if ((this.SacuvajArtikalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SacuvajArtikalCompleted(this, new SacuvajArtikalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SacuvajArtikalAsync(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal) {
            this.SacuvajArtikalAsync(artikal, null);
        }
        
        public void SacuvajArtikalAsync(AbcPos.BackOffice.Win.Services.BackendService.Artikal artikal, object userState) {
            if ((this.onBeginSacuvajArtikalDelegate == null)) {
                this.onBeginSacuvajArtikalDelegate = new BeginOperationDelegate(this.OnBeginSacuvajArtikal);
            }
            if ((this.onEndSacuvajArtikalDelegate == null)) {
                this.onEndSacuvajArtikalDelegate = new EndOperationDelegate(this.OnEndSacuvajArtikal);
            }
            if ((this.onSacuvajArtikalCompletedDelegate == null)) {
                this.onSacuvajArtikalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSacuvajArtikalCompleted);
            }
            base.InvokeAsync(this.onBeginSacuvajArtikalDelegate, new object[] {
                        artikal}, this.onEndSacuvajArtikalDelegate, this.onSacuvajArtikalCompletedDelegate, userState);
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndPing(System.IAsyncResult result) {
            base.Channel.EndPing(result);
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginPing(callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            this.EndPing(result);
            return null;
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        public void PingAsync(object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, null, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
    }
}
