#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbcPos.Web.SampleData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Razvoj")]
	public partial class AkordDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRM_Artikli(RM_Artikli instance);
    partial void UpdateRM_Artikli(RM_Artikli instance);
    partial void DeleteRM_Artikli(RM_Artikli instance);
    partial void InsertRM_EanKodovi(RM_EanKodovi instance);
    partial void UpdateRM_EanKodovi(RM_EanKodovi instance);
    partial void DeleteRM_EanKodovi(RM_EanKodovi instance);
    partial void InsertRM_Zalihe(RM_Zalihe instance);
    partial void UpdateRM_Zalihe(RM_Zalihe instance);
    partial void DeleteRM_Zalihe(RM_Zalihe instance);
    #endregion
		
		public AkordDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProdukcijaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AkordDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkordDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkordDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkordDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RM_Artikli> RM_Artiklis
		{
			get
			{
				return this.GetTable<RM_Artikli>();
			}
		}
		
		public System.Data.Linq.Table<RM_EanKodovi> RM_EanKodovis
		{
			get
			{
				return this.GetTable<RM_EanKodovi>();
			}
		}
		
		public System.Data.Linq.Table<RM_Zalihe> RM_Zalihes
		{
			get
			{
				return this.GetTable<RM_Zalihe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RM_Artikli")]
	public partial class RM_Artikli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdSistema;
		
		private long _IdArtikla;
		
		private string _MaticniBroj;
		
		private string _NazivArtikla;
		
		private string _KataloskiBroj;
		
		private System.Nullable<int> _IdBrenda;
		
		private EntitySet<RM_EanKodovi> _RM_EanKodovis;
		
		private EntitySet<RM_Zalihe> _RM_Zalihes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSistemaChanging(string value);
    partial void OnIdSistemaChanged();
    partial void OnIdArtiklaChanging(long value);
    partial void OnIdArtiklaChanged();
    partial void OnMaticniBrojChanging(string value);
    partial void OnMaticniBrojChanged();
    partial void OnNazivArtiklaChanging(string value);
    partial void OnNazivArtiklaChanged();
    partial void OnKataloskiBrojChanging(string value);
    partial void OnKataloskiBrojChanged();
    partial void OnIdBrendaChanging(System.Nullable<int> value);
    partial void OnIdBrendaChanged();
    #endregion
		
		public RM_Artikli()
		{
			this._RM_EanKodovis = new EntitySet<RM_EanKodovi>(new Action<RM_EanKodovi>(this.attach_RM_EanKodovis), new Action<RM_EanKodovi>(this.detach_RM_EanKodovis));
			this._RM_Zalihes = new EntitySet<RM_Zalihe>(new Action<RM_Zalihe>(this.attach_RM_Zalihes), new Action<RM_Zalihe>(this.detach_RM_Zalihes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSistema", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdSistema
		{
			get
			{
				return this._IdSistema;
			}
			set
			{
				if ((this._IdSistema != value))
				{
					this.OnIdSistemaChanging(value);
					this.SendPropertyChanging();
					this._IdSistema = value;
					this.SendPropertyChanged("IdSistema");
					this.OnIdSistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtikla", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IdArtikla
		{
			get
			{
				return this._IdArtikla;
			}
			set
			{
				if ((this._IdArtikla != value))
				{
					this.OnIdArtiklaChanging(value);
					this.SendPropertyChanging();
					this._IdArtikla = value;
					this.SendPropertyChanged("IdArtikla");
					this.OnIdArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaticniBroj", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string MaticniBroj
		{
			get
			{
				return this._MaticniBroj;
			}
			set
			{
				if ((this._MaticniBroj != value))
				{
					this.OnMaticniBrojChanging(value);
					this.SendPropertyChanging();
					this._MaticniBroj = value;
					this.SendPropertyChanged("MaticniBroj");
					this.OnMaticniBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivArtikla", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NazivArtikla
		{
			get
			{
				return this._NazivArtikla;
			}
			set
			{
				if ((this._NazivArtikla != value))
				{
					this.OnNazivArtiklaChanging(value);
					this.SendPropertyChanging();
					this._NazivArtikla = value;
					this.SendPropertyChanged("NazivArtikla");
					this.OnNazivArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KataloskiBroj", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string KataloskiBroj
		{
			get
			{
				return this._KataloskiBroj;
			}
			set
			{
				if ((this._KataloskiBroj != value))
				{
					this.OnKataloskiBrojChanging(value);
					this.SendPropertyChanging();
					this._KataloskiBroj = value;
					this.SendPropertyChanged("KataloskiBroj");
					this.OnKataloskiBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBrenda", DbType="Int")]
		public System.Nullable<int> IdBrenda
		{
			get
			{
				return this._IdBrenda;
			}
			set
			{
				if ((this._IdBrenda != value))
				{
					this.OnIdBrendaChanging(value);
					this.SendPropertyChanging();
					this._IdBrenda = value;
					this.SendPropertyChanged("IdBrenda");
					this.OnIdBrendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RM_Artikli_RM_EanKodovi", Storage="_RM_EanKodovis", ThisKey="IdSistema,IdArtikla", OtherKey="IdSistema,IdArtikla")]
		public EntitySet<RM_EanKodovi> RM_EanKodovis
		{
			get
			{
				return this._RM_EanKodovis;
			}
			set
			{
				this._RM_EanKodovis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RM_Artikli_RM_Zalihe", Storage="_RM_Zalihes", ThisKey="IdSistema,IdArtikla", OtherKey="IdSistema,IdArtikla")]
		public EntitySet<RM_Zalihe> RM_Zalihes
		{
			get
			{
				return this._RM_Zalihes;
			}
			set
			{
				this._RM_Zalihes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RM_EanKodovis(RM_EanKodovi entity)
		{
			this.SendPropertyChanging();
			entity.RM_Artikli = this;
		}
		
		private void detach_RM_EanKodovis(RM_EanKodovi entity)
		{
			this.SendPropertyChanging();
			entity.RM_Artikli = null;
		}
		
		private void attach_RM_Zalihes(RM_Zalihe entity)
		{
			this.SendPropertyChanging();
			entity.RM_Artikli = this;
		}
		
		private void detach_RM_Zalihes(RM_Zalihe entity)
		{
			this.SendPropertyChanging();
			entity.RM_Artikli = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RM_EanKodovi")]
	public partial class RM_EanKodovi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdSistema;
		
		private long _IdArtikla;
		
		private string _EanKod;
		
		private EntityRef<RM_Artikli> _RM_Artikli;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSistemaChanging(string value);
    partial void OnIdSistemaChanged();
    partial void OnIdArtiklaChanging(long value);
    partial void OnIdArtiklaChanged();
    partial void OnEanKodChanging(string value);
    partial void OnEanKodChanged();
    #endregion
		
		public RM_EanKodovi()
		{
			this._RM_Artikli = default(EntityRef<RM_Artikli>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSistema", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdSistema
		{
			get
			{
				return this._IdSistema;
			}
			set
			{
				if ((this._IdSistema != value))
				{
					if (this._RM_Artikli.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSistemaChanging(value);
					this.SendPropertyChanging();
					this._IdSistema = value;
					this.SendPropertyChanged("IdSistema");
					this.OnIdSistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtikla", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IdArtikla
		{
			get
			{
				return this._IdArtikla;
			}
			set
			{
				if ((this._IdArtikla != value))
				{
					if (this._RM_Artikli.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdArtiklaChanging(value);
					this.SendPropertyChanging();
					this._IdArtikla = value;
					this.SendPropertyChanged("IdArtikla");
					this.OnIdArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EanKod", DbType="NVarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EanKod
		{
			get
			{
				return this._EanKod;
			}
			set
			{
				if ((this._EanKod != value))
				{
					this.OnEanKodChanging(value);
					this.SendPropertyChanging();
					this._EanKod = value;
					this.SendPropertyChanged("EanKod");
					this.OnEanKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RM_Artikli_RM_EanKodovi", Storage="_RM_Artikli", ThisKey="IdSistema,IdArtikla", OtherKey="IdSistema,IdArtikla", IsForeignKey=true)]
		public RM_Artikli RM_Artikli
		{
			get
			{
				return this._RM_Artikli.Entity;
			}
			set
			{
				RM_Artikli previousValue = this._RM_Artikli.Entity;
				if (((previousValue != value) 
							|| (this._RM_Artikli.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RM_Artikli.Entity = null;
						previousValue.RM_EanKodovis.Remove(this);
					}
					this._RM_Artikli.Entity = value;
					if ((value != null))
					{
						value.RM_EanKodovis.Add(this);
						this._IdSistema = value.IdSistema;
						this._IdArtikla = value.IdArtikla;
					}
					else
					{
						this._IdSistema = default(string);
						this._IdArtikla = default(long);
					}
					this.SendPropertyChanged("RM_Artikli");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RM_Zalihe")]
	public partial class RM_Zalihe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdSistema;
		
		private string _IdOJ;
		
		private long _IdArtikla;
		
		private int _IdSerije;
		
		private string _IdOdeljka;
		
		private decimal _Zaliha;
		
		private decimal _NabavnaVrednost;
		
		private decimal _ProdajnaVrednost;
		
		private EntityRef<RM_Artikli> _RM_Artikli;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSistemaChanging(string value);
    partial void OnIdSistemaChanged();
    partial void OnIdOJChanging(string value);
    partial void OnIdOJChanged();
    partial void OnIdArtiklaChanging(long value);
    partial void OnIdArtiklaChanged();
    partial void OnIdSerijeChanging(int value);
    partial void OnIdSerijeChanged();
    partial void OnIdOdeljkaChanging(string value);
    partial void OnIdOdeljkaChanged();
    partial void OnZalihaChanging(decimal value);
    partial void OnZalihaChanged();
    partial void OnNabavnaVrednostChanging(decimal value);
    partial void OnNabavnaVrednostChanged();
    partial void OnProdajnaVrednostChanging(decimal value);
    partial void OnProdajnaVrednostChanged();
    #endregion
		
		public RM_Zalihe()
		{
			this._RM_Artikli = default(EntityRef<RM_Artikli>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSistema", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string IdSistema
		{
			get
			{
				return this._IdSistema;
			}
			set
			{
				if ((this._IdSistema != value))
				{
					if (this._RM_Artikli.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSistemaChanging(value);
					this.SendPropertyChanging();
					this._IdSistema = value;
					this.SendPropertyChanged("IdSistema");
					this.OnIdSistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOJ", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string IdOJ
		{
			get
			{
				return this._IdOJ;
			}
			set
			{
				if ((this._IdOJ != value))
				{
					this.OnIdOJChanging(value);
					this.SendPropertyChanging();
					this._IdOJ = value;
					this.SendPropertyChanged("IdOJ");
					this.OnIdOJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtikla", DbType="BigInt NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public long IdArtikla
		{
			get
			{
				return this._IdArtikla;
			}
			set
			{
				if ((this._IdArtikla != value))
				{
					if (this._RM_Artikli.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdArtiklaChanging(value);
					this.SendPropertyChanging();
					this._IdArtikla = value;
					this.SendPropertyChanged("IdArtikla");
					this.OnIdArtiklaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSerije", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int IdSerije
		{
			get
			{
				return this._IdSerije;
			}
			set
			{
				if ((this._IdSerije != value))
				{
					this.OnIdSerijeChanging(value);
					this.SendPropertyChanging();
					this._IdSerije = value;
					this.SendPropertyChanged("IdSerije");
					this.OnIdSerijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOdeljka", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string IdOdeljka
		{
			get
			{
				return this._IdOdeljka;
			}
			set
			{
				if ((this._IdOdeljka != value))
				{
					this.OnIdOdeljkaChanging(value);
					this.SendPropertyChanging();
					this._IdOdeljka = value;
					this.SendPropertyChanged("IdOdeljka");
					this.OnIdOdeljkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zaliha", DbType="Decimal(22,8) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal Zaliha
		{
			get
			{
				return this._Zaliha;
			}
			set
			{
				if ((this._Zaliha != value))
				{
					this.OnZalihaChanging(value);
					this.SendPropertyChanging();
					this._Zaliha = value;
					this.SendPropertyChanged("Zaliha");
					this.OnZalihaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NabavnaVrednost", DbType="Money NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal NabavnaVrednost
		{
			get
			{
				return this._NabavnaVrednost;
			}
			set
			{
				if ((this._NabavnaVrednost != value))
				{
					this.OnNabavnaVrednostChanging(value);
					this.SendPropertyChanging();
					this._NabavnaVrednost = value;
					this.SendPropertyChanged("NabavnaVrednost");
					this.OnNabavnaVrednostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdajnaVrednost", DbType="Money NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal ProdajnaVrednost
		{
			get
			{
				return this._ProdajnaVrednost;
			}
			set
			{
				if ((this._ProdajnaVrednost != value))
				{
					this.OnProdajnaVrednostChanging(value);
					this.SendPropertyChanging();
					this._ProdajnaVrednost = value;
					this.SendPropertyChanged("ProdajnaVrednost");
					this.OnProdajnaVrednostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RM_Artikli_RM_Zalihe", Storage="_RM_Artikli", ThisKey="IdSistema,IdArtikla", OtherKey="IdSistema,IdArtikla", IsForeignKey=true)]
		public RM_Artikli RM_Artikli
		{
			get
			{
				return this._RM_Artikli.Entity;
			}
			set
			{
				RM_Artikli previousValue = this._RM_Artikli.Entity;
				if (((previousValue != value) 
							|| (this._RM_Artikli.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RM_Artikli.Entity = null;
						previousValue.RM_Zalihes.Remove(this);
					}
					this._RM_Artikli.Entity = value;
					if ((value != null))
					{
						value.RM_Zalihes.Add(this);
						this._IdSistema = value.IdSistema;
						this._IdArtikla = value.IdArtikla;
					}
					else
					{
						this._IdSistema = default(string);
						this._IdArtikla = default(long);
					}
					this.SendPropertyChanged("RM_Artikli");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
